### PR TITLE
Support custom package

### PR DESCRIPTION
**Pull request by sskyy**
There are many other frameworks need vite and mdx. This PR adds an option to support custom framework.

### CODE REVIEW

**Comment by brillout** [comment]
I thought MDX only supports React, Preact and Vue?

**Comment by sskyy** [comment]
> I thought MDX only supports React, Preact and Vue?

It can be easily extended to support any framework. Checkout https://github.com/ariesate/engine/tree/master/packages/mdx-axii for example. Axii is a framework I wrote,  I want to use mdx with vite, so I created this PR. I think there maybe other frameworks like Inferno may also need too.

**Comment by sskyy** [comment]
> I thought MDX only supports React, Preact and Vue?

It can be easily extended to support any framework. Checkout https://github.com/ariesate/engine/tree/master/packages/mdx-axii for example. Axii is a framework I wrote,  I want to use mdx with vite, so I created this PR. I think there maybe other frameworks like Inferno may also need too.

**Comment by aleclarson** [comment]
Maybe a better option (from a user perspective) is to fork `vite-plugin-mdx`, have it use `axii` instead of `react`/`preact` and publish it as `@axii/vite-plugin-mdx`. Then users won't need to inject the Axii-specific imports manually.

**Comment by brillout** [comment]
If we find a better option name - `transformOption` is not particularly explicit here - then I think it'd be nice to merge this. Since the plugin is already React/Preact(/Vue) agnostic, this fits well.

**Comment by aleclarson** [comment]
I'm not a fan of forcing users to explicitly configure stuff when it can be avoided. We could provide a Vite hook for `vite-plugin-axii` (or the user if that's preferred) to implement?

```ts
exports default () => {
  return {
    name: 'vite-plugin-axii',
    mdxGetImports(resolveImport) {
      if (resolveImport('axii')) {
        if (!resolveImport('mdx-axii')) {
          throw Error('Must install mdx-axii')
        }
        return [
          `import {createElement} from "axii"`,
          `import {mdx} from "mdx-axii"`,
        ]
      }
    }
  }
}
```

**Comment by sskyy** [comment]
I forked vite-plugin-mdx and closing this pr for now. I'm happy to help when you have a final design to support this feature.

**Comment by brillout** [comment]
@aleclarson Good idea

**Comment by aleclarson** [comment]
Fixed in #25

**Pull request closed without merging**
