### PR TITLE
feat: accept a function for file-specific options

### PR DESCRIPTION
**Pull request by aleclarson**
For applying plugins conditionally based on filename.
```ts
mdx(filename => {
	return {
		remarkPlugins: filename.endsWith('foo.mdx') ? [myPlugin] : []
	}
})
```

### CODE REVIEW

**Comment by aleclarson** [comment]
Merge #15 first

**Review by brillout — APPROVED** [review]

**Comment by brillout** [comment]
LGTM. Only one thing: we should add some (small) docs about #16 and #15.

**Comment by aleclarson** [comment]
Agreed on #16. For #15, the docs already point to https://mdxjs.com/advanced/plugins, which does mention plugin tuples, but not presets. I'd say it's their responsibility to inform people about presets.

**Comment by aleclarson** [comment]
Docs added

**Comment by brillout** [comment]
@aleclarson There are merge conflicts. Feel free to do the merging.

**Pull request merged**
