### PR TITLE
feat: add tsx support for mdx

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Review by brillout — APPROVED** [review]

**Comment by brillout** [comment]
I'm curious; why do you want this?

TS without intellisense is mostly useless and TS cannot handle `.mdx` files, so I'm not sure about the benefits here?

**Comment by xiaoxiangmoe** [comment]
@brillout Because we can copy and paste the TSX code to mdx. And it helps a lot for TS users.

**Comment by aleclarson** [comment]
I'd be curious if performance (in the context of large `.mdx` files) is affected at all by this change, but we don't have benchmarks. Some cursory manual tests would probably be enough. Any volunteers? :P

**Comment by aleclarson** [comment]
Also, as I understand it, the (only?) benefit is that you don't have to strip type assertions when pasting TSX from another file.

**Review by silvenon — CHANGES_REQUESTED** [review]
I don't think this works, have you actually tried it @xiaoxiangmoe? Calling `mdx()` fails with TSX content. A test would definitely need to be included.

Even if it could be made to work, I generally don't think it's a good idea to compile the JSX part of MDX as TSX just because you can, it's not what MDX core does, and it would make this plugin into more than it claims to be. As soon as you switch to some other MDX setup you'd have to rewrite it to JSX anyway. 🤷

**Comment by silvenon** [comment]
> Also, as I understand it, the (only?) benefit is that you don't have to strip type assertions when pasting TSX from another file.

Probably also to be able to use stuff like enums.

**Comment by silvenon** [comment]
The error comes when `@babel/parser` tries to parse it somewhere after applying rehype plugins, I'm not sure where exactly because the stack trace doesn't say.

I was going to suggest a rehype plugin that transpiles TSX into JSX, but I'm not sure if that's possible to do 😬 esbuild doesn't support this yet (https://github.com/evanw/esbuild/issues/735), as for Babel I'm not sure if it's possible to pass a custom TypeScript configuration so it doesn't take the project's one.

That would've been a really nice solution to hack MDX to support TSX because it would put you in control, so I'm sad that it didn't seem to go anywhere. 😢

Anyway, I just wanted to write this to balance out my discouraging words above, so that you know I tried. 😄

**Comment by aleclarson** [comment]
> esbuild doesn't support this yet

We can use [sucrase](https://github.com/alangpierce/sucrase) to strip the types.

**Comment by silvenon** [comment]
But it needs a JSX transform, too, it can't only strip types.

**Comment by aleclarson** [comment]
@silvenon MDX does that

**Comment by aleclarson** [comment]
@silvenon Esbuild does that

**Comment by aleclarson** [comment]
I recommend using this Remark plugin:
https://www.npmjs.com/package/@jamsch/remark-typescript

**Comment by aleclarson** [comment]
Oh whoops, that's for code blocks only. lol

**Comment by aleclarson** [comment]
I think pasting TypeScript into MDX is rare enough that we won't support this.

Your best bet is making a Remark plugin.

**Comment by silvenon** [comment]
@aleclarson I meant that sucrase doesn't seem to be able to turn TSX to JSX, only TSX to JS. `transforms: ["typescript"]` doesn't work for me, I need to configure it with `transforms: ["jsx", "typescript"]`.

But yeah, I agree that this plugin shouldn't be doing this.

**Comment by brillout** [comment]
👍

**Pull request closed without merging**
